# Generated by Django 5.0.6 on 2024-05-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmapping',
            name='full_short_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
